APP_ID: 1
START_DATE: 2025-09-01
END_DATE: 2025-12-01
FREQ: D
COUNTRY: United_States
VIEWS_THRESHOLD: 100

DIMINISHING_RETURNS: 0.9

DEFAULT_RPM: 2
PROCEEDS_PERCENTAGE_FOR_ATTRIBUTION: 0.8
ASSUMED_ROI: 3
RPM_CAP: 4
